/**
 * Seed script — inserts 75 hand-picked problems into the database
 * for the first registered user (or a specific user email).
 *
 * Usage (local, with DATABASE_URL set):
 *   pnpm --filter scripts seed
 *
 * Or run directly:
 *   DATABASE_URL=... node --loader tsx scripts/src/seed-problems.ts
 */

import { db, problemsTable, usersTable } from "@workspace/db";
import { eq } from "drizzle-orm";

// ─── Problem Dataset ──────────────────────────────────────────────────────────
// 75 real problems from LeetCode, Codeforces, HackerRank, AtCoder, GFG
// Spread: ~25 Easy, ~30 Medium, ~20 Hard
const PROBLEMS = [
  // ── EASY ─────────────────────────────────────────────────────────────────
  {
    title: "Two Sum",
    difficulty: "Easy" as const,
    platform: "LeetCode",
    topics: ["Array", "Hash Table"],
    companyTags: ["Google", "Amazon", "Facebook", "Apple"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/two-sum/",
    notes: "Classic hash map approach. O(n) time, O(n) space.",
    attempts: 3,
    dateAdded: "2025-01-10",
    solvedDate: "2025-01-10",
  },
  {
    title: "Valid Parentheses",
    difficulty: "Easy" as const,
    platform: "LeetCode",
    topics: ["Stack", "String"],
    companyTags: ["Google", "Amazon", "Microsoft"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/valid-parentheses/",
    notes: "Use a stack to match opening/closing brackets.",
    attempts: 2,
    dateAdded: "2025-01-12",
    solvedDate: "2025-01-12",
  },
  {
    title: "Reverse Linked List",
    difficulty: "Easy" as const,
    platform: "LeetCode",
    topics: ["Linked List", "Recursion"],
    companyTags: ["Amazon", "Adobe", "Apple"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/reverse-linked-list/",
    notes: "Iterative: prev=null, curr=head. Swap next pointers.",
    attempts: 2,
    dateAdded: "2025-01-15",
    solvedDate: "2025-01-15",
  },
  {
    title: "Best Time to Buy and Sell Stock",
    difficulty: "Easy" as const,
    platform: "LeetCode",
    topics: ["Array", "Dynamic Programming", "Greedy"],
    companyTags: ["Amazon", "Microsoft", "Goldman Sachs"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
    notes: "Track minimum price seen so far. Single pass.",
    attempts: 1,
    dateAdded: "2025-01-18",
    solvedDate: "2025-01-18",
  },
  {
    title: "Maximum Subarray",
    difficulty: "Easy" as const,
    platform: "LeetCode",
    topics: ["Array", "Dynamic Programming", "Divide and Conquer"],
    companyTags: ["Amazon", "LinkedIn", "Microsoft"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/maximum-subarray/",
    notes: "Kadane's Algorithm. currentMax = max(num, currentMax + num).",
    attempts: 2,
    dateAdded: "2025-01-20",
    solvedDate: "2025-01-20",
  },
  {
    title: "Climbing Stairs",
    difficulty: "Easy" as const,
    platform: "LeetCode",
    topics: ["Dynamic Programming", "Math", "Memoization"],
    companyTags: ["Amazon", "Adobe", "Apple"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/climbing-stairs/",
    notes: "Fibonacci pattern. dp[i] = dp[i-1] + dp[i-2].",
    attempts: 1,
    dateAdded: "2025-01-22",
    solvedDate: "2025-01-22",
  },
  {
    title: "Merge Two Sorted Lists",
    difficulty: "Easy" as const,
    platform: "LeetCode",
    topics: ["Linked List", "Recursion"],
    companyTags: ["Amazon", "Microsoft", "Apple"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/merge-two-sorted-lists/",
    notes: "Dummy head trick. Compare heads, advance the smaller.",
    attempts: 2,
    dateAdded: "2025-01-25",
    solvedDate: "2025-01-25",
  },
  {
    title: "Binary Search",
    difficulty: "Easy" as const,
    platform: "LeetCode",
    topics: ["Array", "Binary Search"],
    companyTags: ["Google", "Facebook", "Bloomberg"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/binary-search/",
    notes: "Template: lo=0, hi=n-1, mid=(lo+hi)>>1.",
    attempts: 1,
    dateAdded: "2025-02-01",
    solvedDate: "2025-02-01",
  },
  {
    title: "Flood Fill",
    difficulty: "Easy" as const,
    platform: "LeetCode",
    topics: ["Array", "BFS", "DFS", "Matrix"],
    companyTags: ["Amazon", "Microsoft"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/flood-fill/",
    notes: "DFS/BFS from source pixel, replace color.",
    attempts: 2,
    dateAdded: "2025-02-05",
    solvedDate: "2025-02-05",
  },
  {
    title: "Linked List Cycle",
    difficulty: "Easy" as const,
    platform: "LeetCode",
    topics: ["Linked List", "Two Pointers", "Hash Table"],
    companyTags: ["Amazon", "Bloomberg", "Yahoo"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/linked-list-cycle/",
    notes: "Floyd's cycle detection (slow/fast pointers).",
    attempts: 2,
    dateAdded: "2025-02-08",
    solvedDate: "2025-02-08",
  },
  {
    title: "Invert Binary Tree",
    difficulty: "Easy" as const,
    platform: "LeetCode",
    topics: ["Tree", "BFS", "DFS", "Binary Tree"],
    companyTags: ["Google", "Amazon", "Apple"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/invert-binary-tree/",
    notes: "Swap left/right children recursively.",
    attempts: 1,
    dateAdded: "2025-02-10",
    solvedDate: "2025-02-10",
  },
  {
    title: "Palindrome Number",
    difficulty: "Easy" as const,
    platform: "LeetCode",
    topics: ["Math"],
    companyTags: ["Adobe", "Apple", "Amazon"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/palindrome-number/",
    notes: "Reverse second half of number. Compare with first half.",
    attempts: 2,
    dateAdded: "2025-02-12",
    solvedDate: "2025-02-12",
  },
  {
    title: "Missing Number",
    difficulty: "Easy" as const,
    platform: "LeetCode",
    topics: ["Array", "Hash Table", "Math", "Bit Manipulation"],
    companyTags: ["Microsoft", "Amazon", "Goldman Sachs"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/missing-number/",
    notes: "XOR trick or Gauss sum: n*(n+1)/2 - sum(arr).",
    attempts: 1,
    dateAdded: "2025-02-14",
    solvedDate: "2025-02-14",
  },
  {
    title: "Contains Duplicate",
    difficulty: "Easy" as const,
    platform: "LeetCode",
    topics: ["Array", "Hash Table", "Sorting"],
    companyTags: ["Palantir", "Airbnb", "Amazon"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/contains-duplicate/",
    notes: "HashSet. O(n) time, O(n) space.",
    attempts: 1,
    dateAdded: "2025-02-16",
    solvedDate: "2025-02-16",
  },
  {
    title: "Majority Element",
    difficulty: "Easy" as const,
    platform: "LeetCode",
    topics: ["Array", "Hash Table", "Divide and Conquer", "Sorting"],
    companyTags: ["Google", "Adobe", "Amazon"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/majority-element/",
    notes: "Boyer-Moore Voting Algorithm. O(n) time, O(1) space.",
    attempts: 2,
    dateAdded: "2025-02-18",
    solvedDate: "2025-02-18",
  },
  {
    title: "Sieve of Eratosthenes",
    difficulty: "Easy" as const,
    platform: "GeeksForGeeks",
    topics: ["Math", "Number Theory"],
    companyTags: ["Samsung", "Amazon"],
    status: "Solved" as const,
    solutionLink: "https://practice.geeksforgeeks.org/problems/sieve-of-eratosthenes/",
    notes: "Mark composites. O(n log log n) time.",
    attempts: 1,
    dateAdded: "2025-02-20",
    solvedDate: "2025-02-20",
  },
  {
    title: "Balanced Parentheses",
    difficulty: "Easy" as const,
    platform: "HackerRank",
    topics: ["Stack", "String"],
    companyTags: ["Amazon", "Microsoft"],
    status: "Solved" as const,
    solutionLink: "https://www.hackerrank.com/challenges/balanced-brackets/",
    notes: "Stack-based matching of brackets.",
    attempts: 1,
    dateAdded: "2025-03-01",
    solvedDate: "2025-03-01",
  },
  {
    title: "FizzBuzz",
    difficulty: "Easy" as const,
    platform: "LeetCode",
    topics: ["Math", "String", "Simulation"],
    companyTags: ["Microsoft", "Adobe"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/fizz-buzz/",
    notes: "Loop 1..n. Check divisibility by 15, 3, 5 in order.",
    attempts: 1,
    dateAdded: "2025-03-03",
    solvedDate: "2025-03-03",
  },
  {
    title: "Power of Two",
    difficulty: "Easy" as const,
    platform: "LeetCode",
    topics: ["Math", "Bit Manipulation", "Recursion"],
    companyTags: ["Google", "Apple"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/power-of-two/",
    notes: "n > 0 && (n & (n-1)) == 0.",
    attempts: 1,
    dateAdded: "2025-03-05",
    solvedDate: "2025-03-05",
  },
  {
    title: "Symmetric Tree",
    difficulty: "Easy" as const,
    platform: "LeetCode",
    topics: ["Tree", "BFS", "DFS", "Binary Tree"],
    companyTags: ["LinkedIn", "Bloomberg", "Microsoft"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/symmetric-tree/",
    notes: "Check isMirror(root.left, root.right) recursively.",
    attempts: 2,
    dateAdded: "2025-03-08",
    solvedDate: "2025-03-08",
  },
  {
    title: "Number of Segments in a String",
    difficulty: "Easy" as const,
    platform: "LeetCode",
    topics: ["String"],
    companyTags: [],
    status: "Unsolved" as const,
    solutionLink: "https://leetcode.com/problems/number-of-segments-in-a-string/",
    notes: "",
    attempts: 0,
    dateAdded: "2025-03-10",
    solvedDate: null,
  },
  {
    title: "Watchtower",
    difficulty: "Easy" as const,
    platform: "Codeforces",
    topics: ["Greedy", "Sorting"],
    companyTags: [],
    status: "Solved" as const,
    solutionLink: "https://codeforces.com/problemset/problem/3/B",
    notes: "Sort and greedy pick.",
    attempts: 2,
    dateAdded: "2025-03-12",
    solvedDate: "2025-03-12",
  },
  {
    title: "Divisors",
    difficulty: "Easy" as const,
    platform: "AtCoder",
    topics: ["Math", "Number Theory"],
    companyTags: [],
    status: "Solved" as const,
    solutionLink: "https://atcoder.jp/contests/abc180/tasks/abc180_c",
    notes: "Count divisors up to sqrt(N).",
    attempts: 1,
    dateAdded: "2025-03-14",
    solvedDate: "2025-03-14",
  },
  {
    title: "Reverse String",
    difficulty: "Easy" as const,
    platform: "LeetCode",
    topics: ["Two Pointers", "String"],
    companyTags: ["Google", "Microsoft"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/reverse-string/",
    notes: "Two-pointer swap in-place.",
    attempts: 1,
    dateAdded: "2025-03-16",
    solvedDate: "2025-03-16",
  },
  {
    title: "Pascal's Triangle",
    difficulty: "Easy" as const,
    platform: "LeetCode",
    topics: ["Array", "Dynamic Programming"],
    companyTags: ["Amazon", "Apple"],
    status: "Unsolved" as const,
    solutionLink: "https://leetcode.com/problems/pascals-triangle/",
    notes: "",
    attempts: 0,
    dateAdded: "2025-03-18",
    solvedDate: null,
  },

  // ── MEDIUM ───────────────────────────────────────────────────────────────
  {
    title: "Longest Substring Without Repeating Characters",
    difficulty: "Medium" as const,
    platform: "LeetCode",
    topics: ["Hash Table", "String", "Sliding Window"],
    companyTags: ["Amazon", "Bloomberg", "Uber", "Facebook"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
    notes: "Sliding window + HashMap. Expand right, shrink left on duplicate.",
    attempts: 3,
    dateAdded: "2025-01-11",
    solvedDate: "2025-01-13",
  },
  {
    title: "Add Two Numbers",
    difficulty: "Medium" as const,
    platform: "LeetCode",
    topics: ["Linked List", "Math", "Recursion"],
    companyTags: ["Amazon", "Microsoft", "Bloomberg"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/add-two-numbers/",
    notes: "Simulate addition with carry. Handle different lengths.",
    attempts: 2,
    dateAdded: "2025-01-14",
    solvedDate: "2025-01-15",
  },
  {
    title: "3Sum",
    difficulty: "Medium" as const,
    platform: "LeetCode",
    topics: ["Array", "Two Pointers", "Sorting"],
    companyTags: ["Amazon", "Facebook", "Microsoft", "Adobe"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/3sum/",
    notes: "Sort, fix i, two-pointer for j and k. Skip duplicates carefully.",
    attempts: 4,
    dateAdded: "2025-01-16",
    solvedDate: "2025-01-18",
  },
  {
    title: "Binary Tree Level Order Traversal",
    difficulty: "Medium" as const,
    platform: "LeetCode",
    topics: ["Tree", "BFS", "Binary Tree"],
    companyTags: ["Amazon", "Facebook", "Google"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/binary-tree-level-order-traversal/",
    notes: "BFS queue. Process level by level, push children.",
    attempts: 2,
    dateAdded: "2025-01-19",
    solvedDate: "2025-01-20",
  },
  {
    title: "Number of Islands",
    difficulty: "Medium" as const,
    platform: "LeetCode",
    topics: ["Array", "DFS", "BFS", "Union Find", "Matrix"],
    companyTags: ["Amazon", "Google", "Bloomberg", "Lyft"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/number-of-islands/",
    notes: "DFS flood-fill each unvisited '1', increment counter.",
    attempts: 2,
    dateAdded: "2025-01-21",
    solvedDate: "2025-01-22",
  },
  {
    title: "Coin Change",
    difficulty: "Medium" as const,
    platform: "LeetCode",
    topics: ["Array", "Dynamic Programming", "BFS"],
    companyTags: ["Amazon", "Google", "Microsoft", "Goldman Sachs"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/coin-change/",
    notes: "Bottom-up DP. dp[i] = min coins to make amount i.",
    attempts: 3,
    dateAdded: "2025-01-24",
    solvedDate: "2025-01-26",
  },
  {
    title: "Product of Array Except Self",
    difficulty: "Medium" as const,
    platform: "LeetCode",
    topics: ["Array", "Prefix Sum"],
    companyTags: ["Amazon", "Facebook", "Microsoft", "Lyft"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/product-of-array-except-self/",
    notes: "Prefix + suffix products. No division, O(n) time O(1) extra space.",
    attempts: 2,
    dateAdded: "2025-01-28",
    solvedDate: "2025-01-29",
  },
  {
    title: "Validate Binary Search Tree",
    difficulty: "Medium" as const,
    platform: "LeetCode",
    topics: ["Tree", "DFS", "Binary Search Tree", "Binary Tree"],
    companyTags: ["Amazon", "Facebook", "Bloomberg"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/validate-binary-search-tree/",
    notes: "Pass (min, max) bounds down. node.val must be in (min, max).",
    attempts: 3,
    dateAdded: "2025-02-02",
    solvedDate: "2025-02-03",
  },
  {
    title: "Search in Rotated Sorted Array",
    difficulty: "Medium" as const,
    platform: "LeetCode",
    topics: ["Array", "Binary Search"],
    companyTags: ["Amazon", "Facebook", "Microsoft", "Uber"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
    notes: "Binary search with extra check which half is sorted.",
    attempts: 3,
    dateAdded: "2025-02-04",
    solvedDate: "2025-02-06",
  },
  {
    title: "Top K Frequent Elements",
    difficulty: "Medium" as const,
    platform: "LeetCode",
    topics: ["Array", "Hash Table", "Divide and Conquer", "Sorting", "Heap"],
    companyTags: ["Amazon", "Facebook", "Google", "Yelp"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/top-k-frequent-elements/",
    notes: "Bucket sort by frequency. O(n) time.",
    attempts: 2,
    dateAdded: "2025-02-07",
    solvedDate: "2025-02-08",
  },
  {
    title: "Combination Sum",
    difficulty: "Medium" as const,
    platform: "LeetCode",
    topics: ["Array", "Backtracking"],
    companyTags: ["Amazon", "Facebook", "Airbnb", "Snapchat"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/combination-sum/",
    notes: "Backtrack with start index. Can reuse same element.",
    attempts: 3,
    dateAdded: "2025-02-09",
    solvedDate: "2025-02-11",
  },
  {
    title: "Container With Most Water",
    difficulty: "Medium" as const,
    platform: "LeetCode",
    topics: ["Array", "Two Pointers", "Greedy"],
    companyTags: ["Amazon", "Google", "Bloomberg", "Facebook"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/container-with-most-water/",
    notes: "Two pointers. Move the pointer with smaller height inward.",
    attempts: 2,
    dateAdded: "2025-02-13",
    solvedDate: "2025-02-14",
  },
  {
    title: "Longest Increasing Subsequence",
    difficulty: "Medium" as const,
    platform: "LeetCode",
    topics: ["Array", "Binary Search", "Dynamic Programming"],
    companyTags: ["Amazon", "Microsoft", "Google"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/longest-increasing-subsequence/",
    notes: "Patience sorting (binary search). O(n log n).",
    attempts: 4,
    dateAdded: "2025-02-15",
    solvedDate: "2025-02-17",
  },
  {
    title: "Course Schedule",
    difficulty: "Medium" as const,
    platform: "LeetCode",
    topics: ["DFS", "BFS", "Graph", "Topological Sort"],
    companyTags: ["Amazon", "Facebook", "Google", "Zenefits"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/course-schedule/",
    notes: "Detect cycle in directed graph using DFS (WHITE/GRAY/BLACK states).",
    attempts: 3,
    dateAdded: "2025-02-19",
    solvedDate: "2025-02-21",
  },
  {
    title: "House Robber",
    difficulty: "Medium" as const,
    platform: "LeetCode",
    topics: ["Array", "Dynamic Programming"],
    companyTags: ["Amazon", "Google", "Adobe"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/house-robber/",
    notes: "dp[i] = max(dp[i-2] + nums[i], dp[i-1]).",
    attempts: 2,
    dateAdded: "2025-02-22",
    solvedDate: "2025-02-23",
  },
  {
    title: "Word Search",
    difficulty: "Medium" as const,
    platform: "LeetCode",
    topics: ["Array", "Backtracking", "Matrix", "DFS"],
    companyTags: ["Amazon", "Microsoft", "Bloomberg"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/word-search/",
    notes: "Backtracking DFS on grid. Mark visited, unmark on backtrack.",
    attempts: 4,
    dateAdded: "2025-02-24",
    solvedDate: "2025-02-26",
  },
  {
    title: "Rotate Image",
    difficulty: "Medium" as const,
    platform: "LeetCode",
    topics: ["Array", "Math", "Matrix"],
    companyTags: ["Amazon", "Apple", "Microsoft"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/rotate-image/",
    notes: "Transpose then reverse each row.",
    attempts: 2,
    dateAdded: "2025-02-27",
    solvedDate: "2025-02-28",
  },
  {
    title: "Unique Paths",
    difficulty: "Medium" as const,
    platform: "LeetCode",
    topics: ["Math", "Dynamic Programming", "Combinatorics"],
    companyTags: ["Amazon", "Google", "Goldman Sachs"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/unique-paths/",
    notes: "DP grid. dp[i][j] = dp[i-1][j] + dp[i][j-1].",
    attempts: 1,
    dateAdded: "2025-03-02",
    solvedDate: "2025-03-02",
  },
  {
    title: "Subsets",
    difficulty: "Medium" as const,
    platform: "LeetCode",
    topics: ["Array", "Backtracking", "Bit Manipulation"],
    companyTags: ["Amazon", "Facebook", "Bloomberg"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/subsets/",
    notes: "Iterative: for each element, add to existing subsets.",
    attempts: 2,
    dateAdded: "2025-03-04",
    solvedDate: "2025-03-05",
  },
  {
    title: "Jump Game",
    difficulty: "Medium" as const,
    platform: "LeetCode",
    topics: ["Array", "Dynamic Programming", "Greedy"],
    companyTags: ["Amazon", "Microsoft", "Bloomberg"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/jump-game/",
    notes: "Track max reachable index. Greedy: maxReach = max(maxReach, i+nums[i]).",
    attempts: 2,
    dateAdded: "2025-03-06",
    solvedDate: "2025-03-07",
  },
  {
    title: "Spiral Matrix",
    difficulty: "Medium" as const,
    platform: "LeetCode",
    topics: ["Array", "Matrix", "Simulation"],
    companyTags: ["Amazon", "Microsoft", "Apple"],
    status: "Unsolved" as const,
    solutionLink: "https://leetcode.com/problems/spiral-matrix/",
    notes: "",
    attempts: 1,
    dateAdded: "2025-03-09",
    solvedDate: null,
  },
  {
    title: "Sort Colors",
    difficulty: "Medium" as const,
    platform: "LeetCode",
    topics: ["Array", "Two Pointers", "Sorting"],
    companyTags: ["Amazon", "Microsoft", "Facebook"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/sort-colors/",
    notes: "Dutch National Flag algorithm. Three pointers: lo, mid, hi.",
    attempts: 2,
    dateAdded: "2025-03-11",
    solvedDate: "2025-03-12",
  },
  {
    title: "Codeforces Round 851 - Div 4 Problem E",
    difficulty: "Medium" as const,
    platform: "Codeforces",
    topics: ["Greedy", "Sorting", "Binary Search"],
    companyTags: [],
    status: "Unsolved" as const,
    solutionLink: "https://codeforces.com/contest/1791/problem/E",
    notes: "Binary search on answer + greedy verification.",
    attempts: 2,
    dateAdded: "2025-03-15",
    solvedDate: null,
  },
  {
    title: "Decode String",
    difficulty: "Medium" as const,
    platform: "LeetCode",
    topics: ["String", "Stack", "Recursion"],
    companyTags: ["Amazon", "Google", "Facebook"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/decode-string/",
    notes: "Stack: push currentStr and k when '[' seen. Pop & repeat on ']'.",
    attempts: 3,
    dateAdded: "2025-03-17",
    solvedDate: "2025-03-18",
  },
  {
    title: "Kth Largest Element in an Array",
    difficulty: "Medium" as const,
    platform: "LeetCode",
    topics: ["Array", "Divide and Conquer", "Sorting", "Heap", "Quickselect"],
    companyTags: ["Amazon", "Facebook", "Google", "Microsoft"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/kth-largest-element-in-an-array/",
    notes: "Min-heap of size k. O(n log k). Or QuickSelect O(n) average.",
    attempts: 2,
    dateAdded: "2025-03-19",
    solvedDate: "2025-03-20",
  },
  {
    title: "Maximum Product Subarray",
    difficulty: "Medium" as const,
    platform: "LeetCode",
    topics: ["Array", "Dynamic Programming"],
    companyTags: ["Amazon", "LinkedIn", "Google"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/maximum-product-subarray/",
    notes: "Track max and min products. Negatives flip max/min.",
    attempts: 3,
    dateAdded: "2025-03-21",
    solvedDate: "2025-03-22",
  },
  {
    title: "Letter Combinations of a Phone Number",
    difficulty: "Medium" as const,
    platform: "LeetCode",
    topics: ["Hash Table", "String", "Backtracking"],
    companyTags: ["Amazon", "Facebook", "Google"],
    status: "Unsolved" as const,
    solutionLink: "https://leetcode.com/problems/letter-combinations-of-a-phone-number/",
    notes: "",
    attempts: 1,
    dateAdded: "2025-03-23",
    solvedDate: null,
  },
  {
    title: "LRU Cache",
    difficulty: "Medium" as const,
    platform: "LeetCode",
    topics: ["Hash Table", "Linked List", "Design", "Doubly-Linked List"],
    companyTags: ["Amazon", "Google", "Facebook", "Microsoft"],
    status: "Unsolved" as const,
    solutionLink: "https://leetcode.com/problems/lru-cache/",
    notes: "HashMap + Doubly linked list. O(1) get/put.",
    attempts: 2,
    dateAdded: "2025-03-25",
    solvedDate: null,
  },
  {
    title: "ABC - Subsequence",
    difficulty: "Medium" as const,
    platform: "AtCoder",
    topics: ["Dynamic Programming", "String"],
    companyTags: [],
    status: "Solved" as const,
    solutionLink: "https://atcoder.jp/contests/abc185/tasks/abc185_e",
    notes: "DP counting subsequences.",
    attempts: 2,
    dateAdded: "2025-04-01",
    solvedDate: "2025-04-02",
  },
  {
    title: "Min Stack",
    difficulty: "Medium" as const,
    platform: "LeetCode",
    topics: ["Stack", "Design"],
    companyTags: ["Amazon", "Bloomberg", "JPMorgan"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/min-stack/",
    notes: "Two stacks: one main, one tracking minimums.",
    attempts: 1,
    dateAdded: "2025-04-03",
    solvedDate: "2025-04-03",
  },

  // ── HARD ─────────────────────────────────────────────────────────────────
  {
    title: "Median of Two Sorted Arrays",
    difficulty: "Hard" as const,
    platform: "LeetCode",
    topics: ["Array", "Binary Search", "Divide and Conquer"],
    companyTags: ["Google", "Amazon", "Apple", "Microsoft"],
    status: "Unsolved" as const,
    solutionLink: "https://leetcode.com/problems/median-of-two-sorted-arrays/",
    notes: "Binary search on smaller array partition. O(log(min(m,n))).",
    attempts: 3,
    dateAdded: "2025-01-25",
    solvedDate: null,
  },
  {
    title: "Trapping Rain Water",
    difficulty: "Hard" as const,
    platform: "LeetCode",
    topics: ["Array", "Two Pointers", "Dynamic Programming", "Stack", "Monotonic Stack"],
    companyTags: ["Amazon", "Google", "Facebook", "Bloomberg"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/trapping-rain-water/",
    notes: "Two-pointer approach. Track leftMax and rightMax.",
    attempts: 4,
    dateAdded: "2025-02-01",
    solvedDate: "2025-02-04",
  },
  {
    title: "Merge k Sorted Lists",
    difficulty: "Hard" as const,
    platform: "LeetCode",
    topics: ["Linked List", "Divide and Conquer", "Heap", "Merge Sort"],
    companyTags: ["Amazon", "Facebook", "Google", "Uber"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/merge-k-sorted-lists/",
    notes: "Min-heap of (val, node). Extract min, push next. O(n log k).",
    attempts: 3,
    dateAdded: "2025-02-05",
    solvedDate: "2025-02-07",
  },
  {
    title: "Regular Expression Matching",
    difficulty: "Hard" as const,
    platform: "LeetCode",
    topics: ["String", "Dynamic Programming", "Recursion"],
    companyTags: ["Google", "Facebook", "Airbnb"],
    status: "Unsolved" as const,
    solutionLink: "https://leetcode.com/problems/regular-expression-matching/",
    notes: "DP table. Handle '.' and '*' edge cases.",
    attempts: 2,
    dateAdded: "2025-02-10",
    solvedDate: null,
  },
  {
    title: "Word Ladder",
    difficulty: "Hard" as const,
    platform: "LeetCode",
    topics: ["Hash Table", "String", "BFS"],
    companyTags: ["Amazon", "Facebook", "Snapchat"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/word-ladder/",
    notes: "BFS. For each word, try all 1-char changes. Use word set.",
    attempts: 4,
    dateAdded: "2025-02-16",
    solvedDate: "2025-02-19",
  },
  {
    title: "N-Queens",
    difficulty: "Hard" as const,
    platform: "LeetCode",
    topics: ["Array", "Backtracking"],
    companyTags: ["Amazon", "Apple"],
    status: "Unsolved" as const,
    solutionLink: "https://leetcode.com/problems/n-queens/",
    notes: "Backtracking. Track used cols, diag1, diag2.",
    attempts: 2,
    dateAdded: "2025-02-25",
    solvedDate: null,
  },
  {
    title: "Sliding Window Maximum",
    difficulty: "Hard" as const,
    platform: "LeetCode",
    topics: ["Array", "Queue", "Sliding Window", "Heap", "Monotonic Queue"],
    companyTags: ["Amazon", "Google", "Facebook"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/sliding-window-maximum/",
    notes: "Monotonic deque. Maintain decreasing window from front to back.",
    attempts: 3,
    dateAdded: "2025-03-03",
    solvedDate: "2025-03-05",
  },
  {
    title: "Longest Valid Parentheses",
    difficulty: "Hard" as const,
    platform: "LeetCode",
    topics: ["String", "Dynamic Programming", "Stack"],
    companyTags: ["Amazon", "Google"],
    status: "Unsolved" as const,
    solutionLink: "https://leetcode.com/problems/longest-valid-parentheses/",
    notes: "Stack-based: push index. DP approach also viable.",
    attempts: 1,
    dateAdded: "2025-03-07",
    solvedDate: null,
  },
  {
    title: "Serialize and Deserialize Binary Tree",
    difficulty: "Hard" as const,
    platform: "LeetCode",
    topics: ["String", "Tree", "DFS", "BFS", "Design", "Binary Tree"],
    companyTags: ["Amazon", "Facebook", "LinkedIn", "Microsoft"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/",
    notes: "Preorder DFS with null markers. Deserialize with queue of tokens.",
    attempts: 3,
    dateAdded: "2025-03-13",
    solvedDate: "2025-03-15",
  },
  {
    title: "Minimum Window Substring",
    difficulty: "Hard" as const,
    platform: "LeetCode",
    topics: ["Hash Table", "String", "Sliding Window"],
    companyTags: ["Amazon", "Facebook", "Google", "LinkedIn"],
    status: "Unsolved" as const,
    solutionLink: "https://leetcode.com/problems/minimum-window-substring/",
    notes: "Sliding window with char freq map. Expand right, shrink left.",
    attempts: 3,
    dateAdded: "2025-03-20",
    solvedDate: null,
  },
  {
    title: "Edit Distance",
    difficulty: "Hard" as const,
    platform: "LeetCode",
    topics: ["String", "Dynamic Programming"],
    companyTags: ["Amazon", "Google", "Microsoft"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/edit-distance/",
    notes: "2D DP. dp[i][j] = min(insert, delete, replace).",
    attempts: 3,
    dateAdded: "2025-03-22",
    solvedDate: "2025-03-24",
  },
  {
    title: "Maximal Rectangle",
    difficulty: "Hard" as const,
    platform: "LeetCode",
    topics: ["Array", "Dynamic Programming", "Stack", "Matrix", "Monotonic Stack"],
    companyTags: ["Amazon", "Google"],
    status: "Unsolved" as const,
    solutionLink: "https://leetcode.com/problems/maximal-rectangle/",
    notes: "Reduce to Largest Rectangle in Histogram per row.",
    attempts: 2,
    dateAdded: "2025-03-26",
    solvedDate: null,
  },
  {
    title: "Codeforces - Div 1 - Colorful Graph",
    difficulty: "Hard" as const,
    platform: "Codeforces",
    topics: ["Graph", "DFS", "Greedy"],
    companyTags: [],
    status: "Unsolved" as const,
    solutionLink: "https://codeforces.com/problemset/problem/1093/G",
    notes: "Complex graph coloring with constraints.",
    attempts: 1,
    dateAdded: "2025-04-05",
    solvedDate: null,
  },
  {
    title: "Strange Printer",
    difficulty: "Hard" as const,
    platform: "LeetCode",
    topics: ["String", "Dynamic Programming"],
    companyTags: ["Google"],
    status: "Unsolved" as const,
    solutionLink: "https://leetcode.com/problems/strange-printer/",
    notes: "Interval DP. dp[i][j] = min turns to print s[i..j].",
    attempts: 1,
    dateAdded: "2025-04-07",
    solvedDate: null,
  },
  {
    title: "Largest Rectangle in Histogram",
    difficulty: "Hard" as const,
    platform: "LeetCode",
    topics: ["Array", "Stack", "Monotonic Stack"],
    companyTags: ["Amazon", "Google", "Facebook"],
    status: "Solved" as const,
    solutionLink: "https://leetcode.com/problems/largest-rectangle-in-histogram/",
    notes: "Monotonic increasing stack. Track (index, height) pairs.",
    attempts: 4,
    dateAdded: "2025-04-09",
    solvedDate: "2025-04-12",
  },
  {
    title: "Hard Knapsack - Codeforces",
    difficulty: "Hard" as const,
    platform: "Codeforces",
    topics: ["Dynamic Programming", "Greedy"],
    companyTags: [],
    status: "Unsolved" as const,
    solutionLink: "https://codeforces.com/problemset/problem/1422/D",
    notes: "Knapsack with large constraints.",
    attempts: 2,
    dateAdded: "2025-04-14",
    solvedDate: null,
  },
  {
    title: "Knight Dialer",
    difficulty: "Hard" as const,
    platform: "HackerRank",
    topics: ["Dynamic Programming", "Graph"],
    companyTags: ["Google", "Amazon"],
    status: "Unsolved" as const,
    solutionLink: "https://www.hackerrank.com/challenges/knight-dialer/",
    notes: "DP. Precompute knight moves for each digit.",
    attempts: 1,
    dateAdded: "2025-04-16",
    solvedDate: null,
  },
] as const;

// ─── Main Seed Function ───────────────────────────────────────────────────────
async function seed() {
  const targetEmail = process.env.SEED_USER_EMAIL;

  let user: { id: number; email: string } | undefined;

  if (targetEmail) {
    const rows = await db
      .select({ id: usersTable.id, email: usersTable.email })
      .from(usersTable)
      .where(eq(usersTable.email, targetEmail.toLowerCase()))
      .limit(1);
    user = rows[0];
    if (!user) {
      console.error(`❌ No user found with email: ${targetEmail}`);
      process.exit(1);
    }
  } else {
    // Default: first registered user
    const rows = await db
      .select({ id: usersTable.id, email: usersTable.email })
      .from(usersTable)
      .limit(1);
    user = rows[0];
    if (!user) {
      console.error("❌ No users found in the database. Please register first, then run the seed.");
      process.exit(1);
    }
  }

  console.log(`🌱 Seeding ${PROBLEMS.length} problems for user: ${user.email} (id=${user.id})`);

  // Check for existing problems to avoid duplicates
  const existing = await db
    .select({ title: problemsTable.title })
    .from(problemsTable)
    .where(eq(problemsTable.userId, user.id));

  const existingTitles = new Set(existing.map((e: any) => e.title.toLowerCase()));
  const toInsert = PROBLEMS.filter((p) => !existingTitles.has(p.title.toLowerCase()));

  if (toInsert.length === 0) {
    console.log("✅ All problems already seeded. Nothing to insert.");
    process.exit(0);
  }

  const rows = toInsert.map((p) => ({
    userId: user.id,
    title: p.title,
    difficulty: p.difficulty,
    platform: p.platform,
    topics: [...p.topics],
    companyTags: [...p.companyTags],
    status: p.status,
    favorite: false,
    bookmark: false,
    notes: p.notes,
    solutionLink: p.solutionLink,
    dateAdded: p.dateAdded,
    solvedDate: p.solvedDate ?? null,
    attempts: p.attempts,
  }));

  await db.insert(problemsTable).values(rows);

  const stats = {
    Easy: rows.filter((r) => r.difficulty === "Easy").length,
    Medium: rows.filter((r) => r.difficulty === "Medium").length,
    Hard: rows.filter((r) => r.difficulty === "Hard").length,
  };

  console.log(`✅ Inserted ${rows.length} problems:`);
  console.log(`   🟢 Easy:   ${stats.Easy}`);
  console.log(`   🟡 Medium: ${stats.Medium}`);
  console.log(`   🔴 Hard:   ${stats.Hard}`);
  console.log(`   ⏩ Skipped (duplicates): ${PROBLEMS.length - rows.length}`);
}

seed().catch((err) => {
  console.error("❌ Seed failed:", err);
  process.exit(1);
});
