import { Router, type IRouter } from "express";
import { eq } from "drizzle-orm";
import { db, problemsTable } from "@workspace/db";
import { requireAuth } from "../middlewares/auth.js";

const router: IRouter = Router();

// ─── Seed Problems Dataset ────────────────────────────────────────────────────
const SEED_PROBLEMS = [
  // ── EASY (25) ─────────────────────────────────────────────────────────────
  {
    title: "Two Sum",
    difficulty: "Easy",
    platform: "LeetCode",
    topics: ["Array", "Hash Table"],
    companyTags: ["Google", "Amazon", "Facebook", "Apple"],
    status: "Solved",
    solutionLink: "https://leetcode.com/problems/two-sum/",
    notes: "Classic hash map approach. O(n) time, O(n) space.",
    attempts: 3,
    dateAdded: "2025-01-10",
    solvedDate: "2025-01-10",
  },
  {
    title: "Valid Parentheses",
    difficulty: "Easy",
    platform: "LeetCode",
    topics: ["Stack", "String"],
    companyTags: ["Google", "Amazon", "Microsoft"],
    status: "Solved",
    solutionLink: "https://leetcode.com/problems/valid-parentheses/",
    notes: "Use a stack to match opening/closing brackets.",
    attempts: 2,
    dateAdded: "2025-01-12",
    solvedDate: "2025-01-12",
  },
  {
    title: "Reverse Linked List",
    difficulty: "Easy",
    platform: "LeetCode",
    topics: ["Linked List", "Recursion"],
    companyTags: ["Amazon", "Adobe", "Apple"],
    status: "Solved",
    solutionLink: "https://leetcode.com/problems/reverse-linked-list/",
    notes: "Iterative: prev=null, curr=head. Swap next pointers.",
    attempts: 2,
    dateAdded: "2025-01-15",
    solvedDate: "2025-01-15",
  },
  {
    title: "Best Time to Buy and Sell Stock",
    difficulty: "Easy",
    platform: "LeetCode",
    topics: ["Array", "Dynamic Programming", "Greedy"],
    companyTags: ["Amazon", "Microsoft", "Goldman Sachs"],
    status: "Solved",
    solutionLink:
      "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
    notes: "Track minimum price seen so far. Single pass.",
    attempts: 1,
    dateAdded: "2025-01-18",
    solvedDate: "2025-01-18",
  },
  {
    title: "Maximum Subarray",
    difficulty: "Easy",
    platform: "LeetCode",
    topics: ["Array", "Dynamic Programming", "Divide and Conquer"],
    companyTags: ["Amazon", "LinkedIn", "Microsoft"],
    status: "Solved",
    solutionLink: "https://leetcode.com/problems/maximum-subarray/",
    notes: "Kadane's Algorithm. currentMax = max(num, currentMax + num).",
    attempts: 2,
    dateAdded: "2025-01-20",
    solvedDate: "2025-01-20",
  },
  {
    title: "Climbing Stairs",
    difficulty: "Easy",
    platform: "LeetCode",
    topics: ["Dynamic Programming", "Math", "Memoization"],
    companyTags: ["Amazon", "Adobe", "Apple"],
    status: "Solved",
    solutionLink: "https://leetcode.com/problems/climbing-stairs/",
    notes: "Fibonacci pattern. dp[i] = dp[i-1] + dp[i-2].",
    attempts: 1,
    dateAdded: "2025-01-22",
    solvedDate: "2025-01-22",
  },
  {
    title: "Merge Two Sorted Lists",
    difficulty: "Easy",
    platform: "LeetCode",
    topics: ["Linked List", "Recursion"],
    companyTags: ["Amazon", "Microsoft", "Apple"],
    status: "Solved",
    solutionLink: "https://leetcode.com/problems/merge-two-sorted-lists/",
    notes: "Dummy head trick. Compare heads, advance the smaller.",
    attempts: 2,
    dateAdded: "2025-01-25",
    solvedDate: "2025-01-25",
  },
  {
    title: "Binary Search",
    difficulty: "Easy",
    platform: "LeetCode",
    topics: ["Array", "Binary Search"],
    companyTags: ["Google", "Facebook", "Bloomberg"],
    status: "Solved",
    solutionLink: "https://leetcode.com/problems/binary-search/",
    notes: "Template: lo=0, hi=n-1, mid=(lo+hi)>>1.",
    attempts: 1,
    dateAdded: "2025-02-01",
    solvedDate: "2025-02-01",
  },
  {
    title: "Flood Fill",
    difficulty: "Easy",
    platform: "LeetCode",
    topics: ["Array", "BFS", "DFS", "Matrix"],
    companyTags: ["Amazon", "Microsoft"],
    status: "Solved",
    solutionLink: "https://leetcode.com/problems/flood-fill/",
    notes: "DFS/BFS from source pixel, replace color.",
    attempts: 2,
    dateAdded: "2025-02-05",
    solvedDate: "2025-02-05",
  },
  {
    title: "Linked List Cycle",
    difficulty: "Easy",
    platform: "LeetCode",
    topics: ["Linked List", "Two Pointers", "Hash Table"],
    companyTags: ["Amazon", "Bloomberg", "Yahoo"],
    status: "Solved",
    solutionLink: "https://leetcode.com/problems/linked-list-cycle/",
    notes: "Floyd's cycle detection (slow/fast pointers).",
    attempts: 2,
    dateAdded: "2025-02-08",
    solvedDate: "2025-02-08",
  },
  {
    title: "Invert Binary Tree",
    difficulty: "Easy",
    platform: "LeetCode",
    topics: ["Tree", "BFS", "DFS", "Binary Tree"],
    companyTags: ["Google", "Amazon", "Apple"],
    status: "Solved",
    solutionLink: "https://leetcode.com/problems/invert-binary-tree/",
    notes: "Swap left/right children recursively.",
    attempts: 1,
    dateAdded: "2025-02-10",
    solvedDate: "2025-02-10",
  },
  {
    title: "Palindrome Number",
    difficulty: "Easy",
    platform: "LeetCode",
    topics: ["Math"],
    companyTags: ["Adobe", "Apple", "Amazon"],
    status: "Solved",
    solutionLink: "https://leetcode.com/problems/palindrome-number/",
    notes: "Reverse second half of number. Compare with first half.",
    attempts: 2,
    dateAdded: "2025-02-12",
    solvedDate: "2025-02-12",
  },
  {
    title: "Missing Number",
    difficulty: "Easy",
    platform: "LeetCode",
    topics: ["Array", "Hash Table", "Math", "Bit Manipulation"],
    companyTags: ["Microsoft", "Amazon", "Goldman Sachs"],
    status: "Solved",
    solutionLink: "https://leetcode.com/problems/missing-number/",
    notes: "XOR trick or Gauss sum: n*(n+1)/2 - sum(arr).",
    attempts: 1,
    dateAdded: "2025-02-14",
    solvedDate: "2025-02-14",
  },
  {
    title: "Contains Duplicate",
    difficulty: "Easy",
    platform: "LeetCode",
    topics: ["Array", "Hash Table", "Sorting"],
    companyTags: ["Palantir", "Airbnb", "Amazon"],
    status: "Solved",
    solutionLink: "https://leetcode.com/problems/contains-duplicate/",
    notes: "HashSet. O(n) time, O(n) space.",
    attempts: 1,
    dateAdded: "2025-02-16",
    solvedDate: "2025-02-16",
  },
  {
    title: "Majority Element",
    difficulty: "Easy",
    platform: "LeetCode",
    topics: ["Array", "Hash Table", "Divide and Conquer", "Sorting"],
    companyTags: ["Google", "Adobe", "Amazon"],
    status: "Solved",
    solutionLink: "https://leetcode.com/problems/majority-element/",
    notes: "Boyer-Moore Voting Algorithm. O(n) time, O(1) space.",
    attempts: 2,
    dateAdded: "2025-02-18",
    solvedDate: "2025-02-18",
  },
  {
    title: "Sieve of Eratosthenes",
    difficulty: "Easy",
    platform: "GeeksForGeeks",
    topics: ["Math", "Number Theory"],
    companyTags: ["Samsung", "Amazon"],
    status: "Solved",
    solutionLink:
      "https://practice.geeksforgeeks.org/problems/sieve-of-eratosthenes/",
    notes: "Mark composites. O(n log log n) time.",
    attempts: 1,
    dateAdded: "2025-02-20",
    solvedDate: "2025-02-20",
  },
  {
    title: "Balanced Parentheses",
    difficulty: "Easy",
    platform: "HackerRank",
    topics: ["Stack", "String"],
    companyTags: ["Amazon", "Microsoft"],
    status: "Solved",
    solutionLink: "https://www.hackerrank.com/challenges/balanced-brackets/",
    notes: "Stack-based matching of brackets.",
    attempts: 1,
    dateAdded: "2025-03-01",
    solvedDate: "2025-03-01",
  },
  {
    title: "FizzBuzz",
    difficulty: "Easy",
    platform: "LeetCode",
    topics: ["Math", "String", "Simulation"],
    companyTags: ["Microsoft", "Adobe"],
    status: "Solved",
    solutionLink: "https://leetcode.com/problems/fizz-buzz/",
    notes: "Loop 1..n. Check divisibility by 15, 3, 5 in order.",
    attempts: 1,
    dateAdded: "2025-03-03",
    solvedDate: "2025-03-03",
  },
  {
    title: "Power of Two",
    difficulty: "Easy",
    platform: "LeetCode",
    topics: ["Math", "Bit Manipulation", "Recursion"],
    companyTags: ["Google", "Apple"],
    status: "Solved",
    solutionLink: "https://leetcode.com/problems/power-of-two/",
    notes: "n > 0 && (n & (n-1)) == 0.",
    attempts: 1,
    dateAdded: "2025-03-05",
    solvedDate: "2025-03-05",
  },
  {
    title: "Symmetric Tree",
    difficulty: "Easy",
    platform: "LeetCode",
    topics: ["Tree", "BFS", "DFS", "Binary Tree"],
    companyTags: ["LinkedIn", "Bloomberg", "Microsoft"],
    status: "Solved",
    solutionLink: "https://leetcode.com/problems/symmetric-tree/",
    notes: "Check isMirror(root.left, root.right) recursively.",
    attempts: 2,
    dateAdded: "2025-03-08",
    solvedDate: "2025-03-08",
  },
  {
    title: "Watchtower",
    difficulty: "Easy",
    platform: "Codeforces",
    topics: ["Greedy", "Sorting"],
    companyTags: [],
    status: "Solved",
    solutionLink: "https://codeforces.com/problemset/problem/3/B",
    notes: "Sort and greedy pick.",
    attempts: 2,
    dateAdded: "2025-03-12",
    solvedDate: "2025-03-12",
  },
  {
    title: "Divisors",
    difficulty: "Easy",
    platform: "AtCoder",
    topics: ["Math", "Number Theory"],
    companyTags: [],
    status: "Solved",
    solutionLink: "https://atcoder.jp/contests/abc180/tasks/abc180_c",
    notes: "Count divisors up to sqrt(N).",
    attempts: 1,
    dateAdded: "2025-03-14",
    solvedDate: "2025-03-14",
  },
  {
    title: "Reverse String",
    difficulty: "Easy",
    platform: "LeetCode",
    topics: ["Two Pointers", "String"],
    companyTags: ["Google", "Microsoft"],
    status: "Solved",
    solutionLink: "https://leetcode.com/problems/reverse-string/",
    notes: "Two-pointer swap in-place.",
    attempts: 1,
    dateAdded: "2025-03-16",
    solvedDate: "2025-03-16",
  },
  {
    title: "Pascal's Triangle",
    difficulty: "Easy",
    platform: "LeetCode",
    topics: ["Array", "Dynamic Programming"],
    companyTags: ["Amazon", "Apple"],
    status: "Unsolved",
    solutionLink: "https://leetcode.com/problems/pascals-triangle/",
    notes: "",
    attempts: 0,
    dateAdded: "2025-03-18",
    solvedDate: null,
  },
  {
    title: "Power of Three",
    difficulty: "Easy",
    platform: "LeetCode",
    topics: ["Math", "Recursion"],
    companyTags: [],
    status: "Unsolved",
    solutionLink: "https://leetcode.com/problems/power-of-three/",
    notes: "",
    attempts: 0,
    dateAdded: "2025-03-20",
    solvedDate: null,
  },

  // ── MEDIUM (30) ──────────────────────────────────────────────────────────
  {
    title: "Longest Substring Without Repeating Characters",
    difficulty: "Medium",
    platform: "LeetCode",
    topics: ["Hash Table", "String", "Sliding Window"],
    companyTags: ["Amazon", "Bloomberg", "Uber", "Facebook"],
    status: "Solved",
    solutionLink:
      "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
    notes: "Sliding window + HashMap. Expand right, shrink left on duplicate.",
    attempts: 3,
    dateAdded: "2025-01-11",
    solvedDate: "2025-01-13",
  },
  {
    title: "Add Two Numbers",
    difficulty: "Medium",
    platform: "LeetCode",
    topics: ["Linked List", "Math", "Recursion"],
    companyTags: ["Amazon", "Microsoft", "Bloomberg"],
    status: "Solved",
    solutionLink: "https://leetcode.com/problems/add-two-numbers/",
    notes: "Simulate addition with carry. Handle different lengths.",
    attempts: 2,
    dateAdded: "2025-01-14",
    solvedDate: "2025-01-15",
  },
  {
    title: "3Sum",
    difficulty: "Medium",
    platform: "LeetCode",
    topics: ["Array", "Two Pointers", "Sorting"],
    companyTags: ["Amazon", "Facebook", "Microsoft", "Adobe"],
    status: "Solved",
    solutionLink: "https://leetcode.com/problems/3sum/",
    notes: "Sort, fix i, two-pointer for j and k. Skip duplicates carefully.",
    attempts: 4,
    dateAdded: "2025-01-16",
    solvedDate: "2025-01-18",
  },
  {
    title: "Binary Tree Level Order Traversal",
    difficulty: "Medium",
    platform: "LeetCode",
    topics: ["Tree", "BFS", "Binary Tree"],
    companyTags: ["Amazon", "Facebook", "Google"],
    status: "Solved",
    solutionLink:
      "https://leetcode.com/problems/binary-tree-level-order-traversal/",
    notes: "BFS queue. Process level by level, push children.",
    attempts: 2,
    dateAdded: "2025-01-19",
    solvedDate: "2025-01-20",
  },
  {
    title: "Number of Islands",
    difficulty: "Medium",
    platform: "LeetCode",
    topics: ["Array", "DFS", "BFS", "Union Find", "Matrix"],
    companyTags: ["Amazon", "Google", "Bloomberg", "Lyft"],
    status: "Solved",
    solutionLink: "https://leetcode.com/problems/number-of-islands/",
    notes: "DFS flood-fill each unvisited '1', increment counter.",
    attempts: 2,
    dateAdded: "2025-01-21",
    solvedDate: "2025-01-22",
  },
  {
    title: "Coin Change",
    difficulty: "Medium",
    platform: "LeetCode",
    topics: ["Array", "Dynamic Programming", "BFS"],
    companyTags: ["Amazon", "Google", "Microsoft", "Goldman Sachs"],
    status: "Solved",
    solutionLink: "https://leetcode.com/problems/coin-change/",
    notes: "Bottom-up DP. dp[i] = min coins to make amount i.",
    attempts: 3,
    dateAdded: "2025-01-24",
    solvedDate: "2025-01-26",
  },
  {
    title: "Product of Array Except Self",
    difficulty: "Medium",
    platform: "LeetCode",
    topics: ["Array", "Prefix Sum"],
    companyTags: ["Amazon", "Facebook", "Microsoft", "Lyft"],
    status: "Solved",
    solutionLink: "https://leetcode.com/problems/product-of-array-except-self/",
    notes: "Prefix + suffix products. No division, O(n) time O(1) extra space.",
    attempts: 2,
    dateAdded: "2025-01-28",
    solvedDate: "2025-01-29",
  },
  {
    title: "Validate Binary Search Tree",
    difficulty: "Medium",
    platform: "LeetCode",
    topics: ["Tree", "DFS", "Binary Search Tree", "Binary Tree"],
    companyTags: ["Amazon", "Facebook", "Bloomberg"],
    status: "Solved",
    solutionLink: "https://leetcode.com/problems/validate-binary-search-tree/",
    notes: "Pass (min, max) bounds down. node.val must be in (min, max).",
    attempts: 3,
    dateAdded: "2025-02-02",
    solvedDate: "2025-02-03",
  },
  {
    title: "Search in Rotated Sorted Array",
    difficulty: "Medium",
    platform: "LeetCode",
    topics: ["Array", "Binary Search"],
    companyTags: ["Amazon", "Facebook", "Microsoft", "Uber"],
    status: "Solved",
    solutionLink:
      "https://leetcode.com/problems/search-in-rotated-sorted-array/",
    notes: "Binary search with extra check which half is sorted.",
    attempts: 3,
    dateAdded: "2025-02-04",
    solvedDate: "2025-02-06",
  },
  {
    title: "Top K Frequent Elements",
    difficulty: "Medium",
    platform: "LeetCode",
    topics: ["Array", "Hash Table", "Sorting", "Heap"],
    companyTags: ["Amazon", "Facebook", "Google", "Yelp"],
    status: "Solved",
    solutionLink: "https://leetcode.com/problems/top-k-frequent-elements/",
    notes: "Bucket sort by frequency. O(n) time.",
    attempts: 2,
    dateAdded: "2025-02-07",
    solvedDate: "2025-02-08",
  },
  {
    title: "Combination Sum",
    difficulty: "Medium",
    platform: "LeetCode",
    topics: ["Array", "Backtracking"],
    companyTags: ["Amazon", "Facebook", "Airbnb", "Snapchat"],
    status: "Solved",
    solutionLink: "https://leetcode.com/problems/combination-sum/",
    notes: "Backtrack with start index. Can reuse same element.",
    attempts: 3,
    dateAdded: "2025-02-09",
    solvedDate: "2025-02-11",
  },
  {
    title: "Container With Most Water",
    difficulty: "Medium",
    platform: "LeetCode",
    topics: ["Array", "Two Pointers", "Greedy"],
    companyTags: ["Amazon", "Google", "Bloomberg", "Facebook"],
    status: "Solved",
    solutionLink: "https://leetcode.com/problems/container-with-most-water/",
    notes: "Two pointers. Move the pointer with smaller height inward.",
    attempts: 2,
    dateAdded: "2025-02-13",
    solvedDate: "2025-02-14",
  },
  {
    title: "Longest Increasing Subsequence",
    difficulty: "Medium",
    platform: "LeetCode",
    topics: ["Array", "Binary Search", "Dynamic Programming"],
    companyTags: ["Amazon", "Microsoft", "Google"],
    status: "Solved",
    solutionLink:
      "https://leetcode.com/problems/longest-increasing-subsequence/",
    notes: "Patience sorting (binary search). O(n log n).",
    attempts: 4,
    dateAdded: "2025-02-15",
    solvedDate: "2025-02-17",
  },
  {
    title: "Course Schedule",
    difficulty: "Medium",
    platform: "LeetCode",
    topics: ["DFS", "BFS", "Graph", "Topological Sort"],
    companyTags: ["Amazon", "Facebook", "Google", "Zenefits"],
    status: "Solved",
    solutionLink: "https://leetcode.com/problems/course-schedule/",
    notes:
      "Detect cycle in directed graph using DFS (WHITE/GRAY/BLACK states).",
    attempts: 3,
    dateAdded: "2025-02-19",
    solvedDate: "2025-02-21",
  },
  {
    title: "House Robber",
    difficulty: "Medium",
    platform: "LeetCode",
    topics: ["Array", "Dynamic Programming"],
    companyTags: ["Amazon", "Google", "Adobe"],
    status: "Solved",
    solutionLink: "https://leetcode.com/problems/house-robber/",
    notes: "dp[i] = max(dp[i-2] + nums[i], dp[i-1]).",
    attempts: 2,
    dateAdded: "2025-02-22",
    solvedDate: "2025-02-23",
  },
  {
    title: "Word Search",
    difficulty: "Medium",
    platform: "LeetCode",
    topics: ["Array", "Backtracking", "Matrix", "DFS"],
    companyTags: ["Amazon", "Microsoft", "Bloomberg"],
    status: "Solved",
    solutionLink: "https://leetcode.com/problems/word-search/",
    notes: "Backtracking DFS on grid. Mark visited, unmark on backtrack.",
    attempts: 4,
    dateAdded: "2025-02-24",
    solvedDate: "2025-02-26",
  },
  {
    title: "Rotate Image",
    difficulty: "Medium",
    platform: "LeetCode",
    topics: ["Array", "Math", "Matrix"],
    companyTags: ["Amazon", "Apple", "Microsoft"],
    status: "Solved",
    solutionLink: "https://leetcode.com/problems/rotate-image/",
    notes: "Transpose then reverse each row.",
    attempts: 2,
    dateAdded: "2025-02-27",
    solvedDate: "2025-02-28",
  },
  {
    title: "Unique Paths",
    difficulty: "Medium",
    platform: "LeetCode",
    topics: ["Math", "Dynamic Programming", "Combinatorics"],
    companyTags: ["Amazon", "Google", "Goldman Sachs"],
    status: "Solved",
    solutionLink: "https://leetcode.com/problems/unique-paths/",
    notes: "DP grid. dp[i][j] = dp[i-1][j] + dp[i][j-1].",
    attempts: 1,
    dateAdded: "2025-03-02",
    solvedDate: "2025-03-02",
  },
  {
    title: "Subsets",
    difficulty: "Medium",
    platform: "LeetCode",
    topics: ["Array", "Backtracking", "Bit Manipulation"],
    companyTags: ["Amazon", "Facebook", "Bloomberg"],
    status: "Solved",
    solutionLink: "https://leetcode.com/problems/subsets/",
    notes: "Iterative: for each element, add to existing subsets.",
    attempts: 2,
    dateAdded: "2025-03-04",
    solvedDate: "2025-03-05",
  },
  {
    title: "Jump Game",
    difficulty: "Medium",
    platform: "LeetCode",
    topics: ["Array", "Dynamic Programming", "Greedy"],
    companyTags: ["Amazon", "Microsoft", "Bloomberg"],
    status: "Solved",
    solutionLink: "https://leetcode.com/problems/jump-game/",
    notes:
      "Track max reachable index. Greedy: maxReach = max(maxReach, i+nums[i]).",
    attempts: 2,
    dateAdded: "2025-03-06",
    solvedDate: "2025-03-07",
  },
  {
    title: "Spiral Matrix",
    difficulty: "Medium",
    platform: "LeetCode",
    topics: ["Array", "Matrix", "Simulation"],
    companyTags: ["Amazon", "Microsoft", "Apple"],
    status: "Unsolved",
    solutionLink: "https://leetcode.com/problems/spiral-matrix/",
    notes: "",
    attempts: 1,
    dateAdded: "2025-03-09",
    solvedDate: null,
  },
  {
    title: "Sort Colors",
    difficulty: "Medium",
    platform: "LeetCode",
    topics: ["Array", "Two Pointers", "Sorting"],
    companyTags: ["Amazon", "Microsoft", "Facebook"],
    status: "Solved",
    solutionLink: "https://leetcode.com/problems/sort-colors/",
    notes: "Dutch National Flag algorithm. Three pointers: lo, mid, hi.",
    attempts: 2,
    dateAdded: "2025-03-11",
    solvedDate: "2025-03-12",
  },
  {
    title: "Decode String",
    difficulty: "Medium",
    platform: "LeetCode",
    topics: ["String", "Stack", "Recursion"],
    companyTags: ["Amazon", "Google", "Facebook"],
    status: "Solved",
    solutionLink: "https://leetcode.com/problems/decode-string/",
    notes: "Stack: push currentStr and k when '[' seen. Pop & repeat on ']'.",
    attempts: 3,
    dateAdded: "2025-03-17",
    solvedDate: "2025-03-18",
  },
  {
    title: "Kth Largest Element in an Array",
    difficulty: "Medium",
    platform: "LeetCode",
    topics: ["Array", "Sorting", "Heap", "Quickselect"],
    companyTags: ["Amazon", "Facebook", "Google", "Microsoft"],
    status: "Solved",
    solutionLink:
      "https://leetcode.com/problems/kth-largest-element-in-an-array/",
    notes: "Min-heap of size k. O(n log k). Or QuickSelect O(n) average.",
    attempts: 2,
    dateAdded: "2025-03-19",
    solvedDate: "2025-03-20",
  },
  {
    title: "Maximum Product Subarray",
    difficulty: "Medium",
    platform: "LeetCode",
    topics: ["Array", "Dynamic Programming"],
    companyTags: ["Amazon", "LinkedIn", "Google"],
    status: "Solved",
    solutionLink: "https://leetcode.com/problems/maximum-product-subarray/",
    notes: "Track max and min products. Negatives flip max/min.",
    attempts: 3,
    dateAdded: "2025-03-21",
    solvedDate: "2025-03-22",
  },
  {
    title: "Letter Combinations of a Phone Number",
    difficulty: "Medium",
    platform: "LeetCode",
    topics: ["Hash Table", "String", "Backtracking"],
    companyTags: ["Amazon", "Facebook", "Google"],
    status: "Unsolved",
    solutionLink:
      "https://leetcode.com/problems/letter-combinations-of-a-phone-number/",
    notes: "",
    attempts: 1,
    dateAdded: "2025-03-23",
    solvedDate: null,
  },
  {
    title: "LRU Cache",
    difficulty: "Medium",
    platform: "LeetCode",
    topics: ["Hash Table", "Linked List", "Design", "Doubly-Linked List"],
    companyTags: ["Amazon", "Google", "Facebook", "Microsoft"],
    status: "Unsolved",
    solutionLink: "https://leetcode.com/problems/lru-cache/",
    notes: "HashMap + Doubly linked list. O(1) get/put.",
    attempts: 2,
    dateAdded: "2025-03-25",
    solvedDate: null,
  },
  {
    title: "Min Stack",
    difficulty: "Medium",
    platform: "LeetCode",
    topics: ["Stack", "Design"],
    companyTags: ["Amazon", "Bloomberg", "JPMorgan"],
    status: "Solved",
    solutionLink: "https://leetcode.com/problems/min-stack/",
    notes: "Two stacks: one main, one tracking minimums.",
    attempts: 1,
    dateAdded: "2025-04-03",
    solvedDate: "2025-04-03",
  },
  {
    title: "ABC Subsequence DP",
    difficulty: "Medium",
    platform: "AtCoder",
    topics: ["Dynamic Programming", "String"],
    companyTags: [],
    status: "Solved",
    solutionLink: "https://atcoder.jp/contests/abc185/tasks/abc185_e",
    notes: "DP counting subsequences.",
    attempts: 2,
    dateAdded: "2025-04-01",
    solvedDate: "2025-04-02",
  },
  {
    title: "Codeforces Binary Search on Answer",
    difficulty: "Medium",
    platform: "Codeforces",
    topics: ["Greedy", "Sorting", "Binary Search"],
    companyTags: [],
    status: "Unsolved",
    solutionLink: "https://codeforces.com/contest/1791/problem/E",
    notes: "Binary search on answer + greedy verification.",
    attempts: 2,
    dateAdded: "2025-03-15",
    solvedDate: null,
  },

  // ── HARD (20) ─────────────────────────────────────────────────────────────
  {
    title: "Median of Two Sorted Arrays",
    difficulty: "Hard",
    platform: "LeetCode",
    topics: ["Array", "Binary Search", "Divide and Conquer"],
    companyTags: ["Google", "Amazon", "Apple", "Microsoft"],
    status: "Unsolved",
    solutionLink: "https://leetcode.com/problems/median-of-two-sorted-arrays/",
    notes: "Binary search on smaller array partition. O(log(min(m,n))).",
    attempts: 3,
    dateAdded: "2025-01-25",
    solvedDate: null,
  },
  {
    title: "Trapping Rain Water",
    difficulty: "Hard",
    platform: "LeetCode",
    topics: [
      "Array",
      "Two Pointers",
      "Dynamic Programming",
      "Stack",
      "Monotonic Stack",
    ],
    companyTags: ["Amazon", "Google", "Facebook", "Bloomberg"],
    status: "Solved",
    solutionLink: "https://leetcode.com/problems/trapping-rain-water/",
    notes: "Two-pointer approach. Track leftMax and rightMax.",
    attempts: 4,
    dateAdded: "2025-02-01",
    solvedDate: "2025-02-04",
  },
  {
    title: "Merge k Sorted Lists",
    difficulty: "Hard",
    platform: "LeetCode",
    topics: ["Linked List", "Divide and Conquer", "Heap", "Merge Sort"],
    companyTags: ["Amazon", "Facebook", "Google", "Uber"],
    status: "Solved",
    solutionLink: "https://leetcode.com/problems/merge-k-sorted-lists/",
    notes: "Min-heap of (val, node). Extract min, push next. O(n log k).",
    attempts: 3,
    dateAdded: "2025-02-05",
    solvedDate: "2025-02-07",
  },
  {
    title: "Regular Expression Matching",
    difficulty: "Hard",
    platform: "LeetCode",
    topics: ["String", "Dynamic Programming", "Recursion"],
    companyTags: ["Google", "Facebook", "Airbnb"],
    status: "Unsolved",
    solutionLink: "https://leetcode.com/problems/regular-expression-matching/",
    notes: "DP table. Handle '.' and '*' edge cases.",
    attempts: 2,
    dateAdded: "2025-02-10",
    solvedDate: null,
  },
  {
    title: "Word Ladder",
    difficulty: "Hard",
    platform: "LeetCode",
    topics: ["Hash Table", "String", "BFS"],
    companyTags: ["Amazon", "Facebook", "Snapchat"],
    status: "Solved",
    solutionLink: "https://leetcode.com/problems/word-ladder/",
    notes: "BFS. For each word, try all 1-char changes. Use word set.",
    attempts: 4,
    dateAdded: "2025-02-16",
    solvedDate: "2025-02-19",
  },
  {
    title: "N-Queens",
    difficulty: "Hard",
    platform: "LeetCode",
    topics: ["Array", "Backtracking"],
    companyTags: ["Amazon", "Apple"],
    status: "Unsolved",
    solutionLink: "https://leetcode.com/problems/n-queens/",
    notes: "Backtracking. Track used cols, diag1, diag2.",
    attempts: 2,
    dateAdded: "2025-02-25",
    solvedDate: null,
  },
  {
    title: "Sliding Window Maximum",
    difficulty: "Hard",
    platform: "LeetCode",
    topics: ["Array", "Queue", "Sliding Window", "Heap", "Monotonic Queue"],
    companyTags: ["Amazon", "Google", "Facebook"],
    status: "Solved",
    solutionLink: "https://leetcode.com/problems/sliding-window-maximum/",
    notes: "Monotonic deque. Maintain decreasing window from front to back.",
    attempts: 3,
    dateAdded: "2025-03-03",
    solvedDate: "2025-03-05",
  },
  {
    title: "Longest Valid Parentheses",
    difficulty: "Hard",
    platform: "LeetCode",
    topics: ["String", "Dynamic Programming", "Stack"],
    companyTags: ["Amazon", "Google"],
    status: "Unsolved",
    solutionLink: "https://leetcode.com/problems/longest-valid-parentheses/",
    notes: "Stack-based: push index. DP approach also viable.",
    attempts: 1,
    dateAdded: "2025-03-07",
    solvedDate: null,
  },
  {
    title: "Serialize and Deserialize Binary Tree",
    difficulty: "Hard",
    platform: "LeetCode",
    topics: ["String", "Tree", "DFS", "BFS", "Design", "Binary Tree"],
    companyTags: ["Amazon", "Facebook", "LinkedIn", "Microsoft"],
    status: "Solved",
    solutionLink:
      "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/",
    notes: "Preorder DFS with null markers. Deserialize with queue of tokens.",
    attempts: 3,
    dateAdded: "2025-03-13",
    solvedDate: "2025-03-15",
  },
  {
    title: "Minimum Window Substring",
    difficulty: "Hard",
    platform: "LeetCode",
    topics: ["Hash Table", "String", "Sliding Window"],
    companyTags: ["Amazon", "Facebook", "Google", "LinkedIn"],
    status: "Unsolved",
    solutionLink: "https://leetcode.com/problems/minimum-window-substring/",
    notes: "Sliding window with char freq map. Expand right, shrink left.",
    attempts: 3,
    dateAdded: "2025-03-20",
    solvedDate: null,
  },
  {
    title: "Edit Distance",
    difficulty: "Hard",
    platform: "LeetCode",
    topics: ["String", "Dynamic Programming"],
    companyTags: ["Amazon", "Google", "Microsoft"],
    status: "Solved",
    solutionLink: "https://leetcode.com/problems/edit-distance/",
    notes: "2D DP. dp[i][j] = min(insert, delete, replace).",
    attempts: 3,
    dateAdded: "2025-03-22",
    solvedDate: "2025-03-24",
  },
  {
    title: "Maximal Rectangle",
    difficulty: "Hard",
    platform: "LeetCode",
    topics: [
      "Array",
      "Dynamic Programming",
      "Stack",
      "Matrix",
      "Monotonic Stack",
    ],
    companyTags: ["Amazon", "Google"],
    status: "Unsolved",
    solutionLink: "https://leetcode.com/problems/maximal-rectangle/",
    notes: "Reduce to Largest Rectangle in Histogram per row.",
    attempts: 2,
    dateAdded: "2025-03-26",
    solvedDate: null,
  },
  {
    title: "Largest Rectangle in Histogram",
    difficulty: "Hard",
    platform: "LeetCode",
    topics: ["Array", "Stack", "Monotonic Stack"],
    companyTags: ["Amazon", "Google", "Facebook"],
    status: "Solved",
    solutionLink:
      "https://leetcode.com/problems/largest-rectangle-in-histogram/",
    notes: "Monotonic increasing stack. Track (index, height) pairs.",
    attempts: 4,
    dateAdded: "2025-04-09",
    solvedDate: "2025-04-12",
  },
  {
    title: "Codeforces Colorful Graph",
    difficulty: "Hard",
    platform: "Codeforces",
    topics: ["Graph", "DFS", "Greedy"],
    companyTags: [],
    status: "Unsolved",
    solutionLink: "https://codeforces.com/problemset/problem/1093/G",
    notes: "Complex graph coloring with constraints.",
    attempts: 1,
    dateAdded: "2025-04-05",
    solvedDate: null,
  },
  {
    title: "Strange Printer",
    difficulty: "Hard",
    platform: "LeetCode",
    topics: ["String", "Dynamic Programming"],
    companyTags: ["Google"],
    status: "Unsolved",
    solutionLink: "https://leetcode.com/problems/strange-printer/",
    notes: "Interval DP. dp[i][j] = min turns to print s[i..j].",
    attempts: 1,
    dateAdded: "2025-04-07",
    solvedDate: null,
  },
  {
    title: "Hard Knapsack Codeforces",
    difficulty: "Hard",
    platform: "Codeforces",
    topics: ["Dynamic Programming", "Greedy"],
    companyTags: [],
    status: "Unsolved",
    solutionLink: "https://codeforces.com/problemset/problem/1422/D",
    notes: "Knapsack with large constraints.",
    attempts: 2,
    dateAdded: "2025-04-14",
    solvedDate: null,
  },
  {
    title: "Knight Dialer",
    difficulty: "Hard",
    platform: "HackerRank",
    topics: ["Dynamic Programming", "Graph"],
    companyTags: ["Google", "Amazon"],
    status: "Unsolved",
    solutionLink: "https://www.hackerrank.com/challenges/knight-dialer/",
    notes: "DP. Precompute knight moves for each digit.",
    attempts: 1,
    dateAdded: "2025-04-16",
    solvedDate: null,
  },
  {
    title: "Maximum Gap",
    difficulty: "Hard",
    platform: "LeetCode",
    topics: ["Array", "Sorting", "Bucket Sort"],
    companyTags: ["Amazon"],
    status: "Unsolved",
    solutionLink: "https://leetcode.com/problems/maximum-gap/",
    notes: "Bucket sort / Radix sort for O(n) solution.",
    attempts: 1,
    dateAdded: "2025-04-18",
    solvedDate: null,
  },
  {
    title: "Russian Doll Envelopes",
    difficulty: "Hard",
    platform: "LeetCode",
    topics: ["Array", "Binary Search", "Dynamic Programming", "Sorting"],
    companyTags: ["Amazon", "Google"],
    status: "Unsolved",
    solutionLink: "https://leetcode.com/problems/russian-doll-envelopes/",
    notes: "Sort by width ASC, height DESC. LIS on heights.",
    attempts: 2,
    dateAdded: "2025-04-20",
    solvedDate: null,
  },
  {
    title: "Palindrome Pairs",
    difficulty: "Hard",
    platform: "LeetCode",
    topics: ["Array", "Hash Table", "String", "Trie"],
    companyTags: ["Airbnb", "Google"],
    status: "Unsolved",
    solutionLink: "https://leetcode.com/problems/palindrome-pairs/",
    notes: "HashMap of reversed words. Check prefix/suffix palindromes.",
    attempts: 1,
    dateAdded: "2025-04-22",
    solvedDate: null,
  },
] as const;

type SeedDifficulty = "Easy" | "Medium" | "Hard";

type SeedBlueprint = {
  platform: string;
  items: Array<{
    title: string;
    difficulty: SeedDifficulty;
    solutionLink: string;
    topics: string[];
    notes: string;
  }>;
};

const NON_LEETCODE_BLUEPRINT: SeedBlueprint[] = [
  {
    platform: "Codeforces",
    items: [
      {
        title: "Watermelon",
        difficulty: "Easy",
        solutionLink: "https://codeforces.com/problemset/problem/4/A",
        topics: ["Math", "Brute Force"],
        notes: "Check if weight is even and greater than 2.",
      },
      {
        title: "Way Too Long Words",
        difficulty: "Easy",
        solutionLink: "https://codeforces.com/problemset/problem/71/A",
        topics: ["String", "Implementation"],
        notes: "Compress middle characters for long words.",
      },
      {
        title: "Bit++",
        difficulty: "Easy",
        solutionLink: "https://codeforces.com/problemset/problem/282/A",
        topics: ["Implementation"],
        notes: "Increment or decrement counter by operation token.",
      },
      {
        title: "Petya and Strings",
        difficulty: "Easy",
        solutionLink: "https://codeforces.com/problemset/problem/112/A",
        topics: ["String"],
        notes: "Case-insensitive lexicographical comparison.",
      },
      {
        title: "Helpful Maths",
        difficulty: "Easy",
        solutionLink: "https://codeforces.com/problemset/problem/339/A",
        topics: ["Sorting", "String"],
        notes: "Split by +, sort digits, join back.",
      },
      {
        title: "Theatre Square",
        difficulty: "Easy",
        solutionLink: "https://codeforces.com/problemset/problem/1/A",
        topics: ["Math"],
        notes: "Use ceiling division for both dimensions.",
      },
      {
        title: "Next Round",
        difficulty: "Medium",
        solutionLink: "https://codeforces.com/problemset/problem/158/A",
        topics: ["Implementation", "Array"],
        notes: "Count scores >= k-th score and > 0.",
      },
      {
        title: "Stones on the Table",
        difficulty: "Medium",
        solutionLink: "https://codeforces.com/problemset/problem/266/A",
        topics: ["String", "Greedy"],
        notes: "Count adjacent equal colors.",
      },
      {
        title: "Beautiful Matrix",
        difficulty: "Medium",
        solutionLink: "https://codeforces.com/problemset/problem/263/A",
        topics: ["Matrix", "Math"],
        notes: "Find 1 and compute Manhattan distance to center.",
      },
      {
        title: "Presents",
        difficulty: "Medium",
        solutionLink: "https://codeforces.com/problemset/problem/136/A",
        topics: ["Array", "Implementation"],
        notes: "Invert permutation mapping.",
      },
      {
        title: "Queue at the School",
        difficulty: "Medium",
        solutionLink: "https://codeforces.com/problemset/problem/266/B",
        topics: ["Simulation", "String"],
        notes: "Simulate swaps in rounds with index skip.",
      },
      {
        title: "Young Physicist",
        difficulty: "Medium",
        solutionLink: "https://codeforces.com/problemset/problem/69/A",
        topics: ["Math", "Implementation"],
        notes: "Vector sum should be zero in all dimensions.",
      },
      {
        title: "Arrival of the General",
        difficulty: "Hard",
        solutionLink: "https://codeforces.com/problemset/problem/144/A",
        topics: ["Greedy", "Array"],
        notes: "Find farthest max and nearest min positions.",
      },
      {
        title: "Lucky Division",
        difficulty: "Hard",
        solutionLink: "https://codeforces.com/problemset/problem/122/A",
        topics: ["Number Theory", "Brute Force"],
        notes: "Test divisibility by all lucky numbers.",
      },
      {
        title: "Word Capitalization",
        difficulty: "Hard",
        solutionLink: "https://codeforces.com/problemset/problem/281/A",
        topics: ["String", "Implementation"],
        notes: "Uppercase the first character only.",
      },
    ],
  },
  {
    platform: "AtCoder",
    items: [
      {
        title: "Welcome to AtCoder",
        difficulty: "Easy",
        solutionLink: "https://atcoder.jp/contests/practice/tasks/practice_1",
        topics: ["Implementation"],
        notes: "Read mixed input and print formatted output.",
      },
      {
        title: "Placing Marbles",
        difficulty: "Easy",
        solutionLink: "https://atcoder.jp/contests/abs/tasks/abc081_a",
        topics: ["String", "Counting"],
        notes: "Count number of ones in a 3-char string.",
      },
      {
        title: "Coins",
        difficulty: "Easy",
        solutionLink: "https://atcoder.jp/contests/abs/tasks/abc087_b",
        topics: ["Brute Force", "Math"],
        notes: "Triple loop bounded by coin counts.",
      },
      {
        title: "Shift only",
        difficulty: "Easy",
        solutionLink: "https://atcoder.jp/contests/abs/tasks/abc081_b",
        topics: ["Math", "Array"],
        notes: "Count global powers of two in all elements.",
      },
      {
        title: "Some Sums",
        difficulty: "Easy",
        solutionLink: "https://atcoder.jp/contests/abs/tasks/abc083_b",
        topics: ["Implementation", "Digit DP"],
        notes: "Iterate numbers and sum if digit-sum in range.",
      },
      {
        title: "Kagami Mochi",
        difficulty: "Easy",
        solutionLink: "https://atcoder.jp/contests/abs/tasks/abc085_b",
        topics: ["Set", "Sorting"],
        notes: "Count distinct diameters.",
      },
      {
        title: "Otoshidama",
        difficulty: "Medium",
        solutionLink: "https://atcoder.jp/contests/abs/tasks/abc085_c",
        topics: ["Brute Force"],
        notes: "Try note counts with bounded loops.",
      },
      {
        title: "Traveling",
        difficulty: "Medium",
        solutionLink: "https://atcoder.jp/contests/abs/tasks/arc089_a",
        topics: ["Math", "Greedy"],
        notes: "Parity and Manhattan reachability checks.",
      },
      {
        title: "Daydream",
        difficulty: "Medium",
        solutionLink: "https://atcoder.jp/contests/abs/tasks/arc065_a",
        topics: ["String", "Greedy"],
        notes: "Reverse string and match known tokens.",
      },
      {
        title: "Frog 1",
        difficulty: "Medium",
        solutionLink: "https://atcoder.jp/contests/dp/tasks/dp_a",
        topics: ["Dynamic Programming"],
        notes: "DP with transition from i-1 and i-2.",
      },
      {
        title: "Frog 2",
        difficulty: "Medium",
        solutionLink: "https://atcoder.jp/contests/dp/tasks/dp_b",
        topics: ["Dynamic Programming"],
        notes: "DP with up to K jumps.",
      },
      {
        title: "Vacation",
        difficulty: "Medium",
        solutionLink: "https://atcoder.jp/contests/dp/tasks/dp_c",
        topics: ["Dynamic Programming"],
        notes: "DP by day and previous activity.",
      },
      {
        title: "Knapsack 1",
        difficulty: "Hard",
        solutionLink: "https://atcoder.jp/contests/dp/tasks/dp_d",
        topics: ["Dynamic Programming", "Knapsack"],
        notes: "Classic 0/1 knapsack by weight.",
      },
      {
        title: "Grid 1",
        difficulty: "Hard",
        solutionLink: "https://atcoder.jp/contests/dp/tasks/dp_h",
        topics: ["Dynamic Programming", "Grid"],
        notes: "Count paths avoiding blocked cells modulo MOD.",
      },
      {
        title: "Longest Path",
        difficulty: "Hard",
        solutionLink: "https://atcoder.jp/contests/dp/tasks/dp_g",
        topics: ["Graph", "DP", "DAG"],
        notes: "Topological order with longest distance DP.",
      },
    ],
  },
  {
    platform: "CodeChef",
    items: [
      {
        title: "INTEST",
        difficulty: "Easy",
        solutionLink: "https://www.codechef.com/problems/INTEST",
        topics: ["Math", "Input Output"],
        notes: "Count numbers divisible by K.",
      },
      {
        title: "FLOW001",
        difficulty: "Easy",
        solutionLink: "https://www.codechef.com/problems/FLOW001",
        topics: ["Implementation"],
        notes: "Print sum for each testcase.",
      },
      {
        title: "HS08TEST",
        difficulty: "Easy",
        solutionLink: "https://www.codechef.com/problems/HS08TEST",
        topics: ["Math", "Implementation"],
        notes: "ATM withdrawal constraints with bank charge.",
      },
      {
        title: "FCTRL2",
        difficulty: "Easy",
        solutionLink: "https://www.codechef.com/problems/FCTRL2",
        topics: ["Math", "Big Integer"],
        notes: "Compute factorial for small n using big integers.",
      },
      {
        title: "TWONMS",
        difficulty: "Easy",
        solutionLink: "https://www.codechef.com/problems/TWONMS",
        topics: ["Math", "Greedy"],
        notes: "Simulate operations parity, compare ratio.",
      },
      {
        title: "LAPIN",
        difficulty: "Easy",
        solutionLink: "https://www.codechef.com/problems/LAPIN",
        topics: ["String", "Hashing"],
        notes: "Compare sorted halves excluding middle char if odd.",
      },
      {
        title: "CARVANS",
        difficulty: "Medium",
        solutionLink: "https://www.codechef.com/problems/CARVANS",
        topics: ["Greedy", "Array"],
        notes: "Maintain minimum speed seen so far.",
      },
      {
        title: "FRGTNLNG",
        difficulty: "Medium",
        solutionLink: "https://www.codechef.com/problems/FRGTNLNG",
        topics: ["String", "Set"],
        notes: "Mark known words from phrases.",
      },
      {
        title: "CNOTE",
        difficulty: "Medium",
        solutionLink: "https://www.codechef.com/problems/CNOTE",
        topics: ["Greedy", "Implementation"],
        notes: "Find notebook with enough pages and low price.",
      },
      {
        title: "AMR15A",
        difficulty: "Medium",
        solutionLink: "https://www.codechef.com/problems/AMR15A",
        topics: ["Array", "Counting"],
        notes: "Count even and odd strengths.",
      },
      {
        title: "SPALNUM",
        difficulty: "Medium",
        solutionLink: "https://www.codechef.com/problems/SPALNUM",
        topics: ["Math", "Palindrome"],
        notes: "Range loop and palindrome test.",
      },
      {
        title: "PRB01",
        difficulty: "Medium",
        solutionLink: "https://www.codechef.com/problems/PRB01",
        topics: ["Number Theory"],
        notes: "Primality check up to sqrt(n).",
      },
      {
        title: "PPSUM",
        difficulty: "Hard",
        solutionLink: "https://www.codechef.com/problems/PPSUM",
        topics: ["Math"],
        notes: "Repeatedly apply triangular number formula.",
      },
      {
        title: "RAINBOWA",
        difficulty: "Hard",
        solutionLink: "https://www.codechef.com/problems/RAINBOWA",
        topics: ["Array", "Two Pointers"],
        notes: "Validate rainbow pattern and symmetry.",
      },
      {
        title: "CHN15A",
        difficulty: "Hard",
        solutionLink: "https://www.codechef.com/problems/CHN15A",
        topics: ["Math", "Implementation"],
        notes: "Count transformed strengths divisible by 7.",
      },
    ],
  },
  {
    platform: "HackerRank",
    items: [
      {
        title: "Sock Merchant",
        difficulty: "Easy",
        solutionLink:
          "https://www.hackerrank.com/challenges/sock-merchant/problem",
        topics: ["Array", "Hash Table"],
        notes: "Count occurrences then sum floor(freq/2).",
      },
      {
        title: "Counting Valleys",
        difficulty: "Easy",
        solutionLink:
          "https://www.hackerrank.com/challenges/counting-valleys/problem",
        topics: ["Greedy", "Simulation"],
        notes: "Track altitude and valley entrances.",
      },
      {
        title: "Jumping on the Clouds",
        difficulty: "Easy",
        solutionLink:
          "https://www.hackerrank.com/challenges/jumping-on-the-clouds/problem",
        topics: ["Greedy", "Array"],
        notes: "Prefer 2-step jump when safe.",
      },
      {
        title: "Repeated String",
        difficulty: "Easy",
        solutionLink:
          "https://www.hackerrank.com/challenges/repeated-string/problem",
        topics: ["Math", "String"],
        notes: "Count 'a' in full repeats and remainder.",
      },
      {
        title: "2D Array - DS",
        difficulty: "Easy",
        solutionLink: "https://www.hackerrank.com/challenges/2d-array/problem",
        topics: ["Array", "Matrix"],
        notes: "Evaluate all hourglass sums.",
      },
      {
        title: "Left Rotation",
        difficulty: "Easy",
        solutionLink:
          "https://www.hackerrank.com/challenges/ctci-array-left-rotation/problem",
        topics: ["Array"],
        notes: "Output by modular index shift.",
      },
      {
        title: "New Year Chaos",
        difficulty: "Medium",
        solutionLink:
          "https://www.hackerrank.com/challenges/new-year-chaos/problem",
        topics: ["Greedy", "Array"],
        notes: "Bounded inversion count near each index.",
      },
      {
        title: "Minimum Swaps 2",
        difficulty: "Medium",
        solutionLink:
          "https://www.hackerrank.com/challenges/minimum-swaps-2/problem",
        topics: ["Graph", "Array"],
        notes: "Cycle decomposition for minimum swaps.",
      },
      {
        title: "Array Manipulation",
        difficulty: "Medium",
        solutionLink: "https://www.hackerrank.com/challenges/crush/problem",
        topics: ["Prefix Sum"],
        notes: "Difference array then prefix max.",
      },
      {
        title: "Balanced Brackets HR",
        difficulty: "Medium",
        solutionLink:
          "https://www.hackerrank.com/challenges/balanced-brackets/problem",
        topics: ["Stack", "String"],
        notes: "Classic stack matching.",
      },
      {
        title: "Queue using Two Stacks",
        difficulty: "Medium",
        solutionLink:
          "https://www.hackerrank.com/challenges/queue-using-two-stacks/problem",
        topics: ["Stack", "Queue"],
        notes: "Amortized O(1) enqueue/dequeue.",
      },
      {
        title: "DFS: Connected Cell in a Grid",
        difficulty: "Medium",
        solutionLink:
          "https://www.hackerrank.com/challenges/connected-cell-in-a-grid/problem",
        topics: ["DFS", "Matrix"],
        notes: "Flood fill with 8-direction movement.",
      },
      {
        title: "Castle on the Grid",
        difficulty: "Hard",
        solutionLink:
          "https://www.hackerrank.com/challenges/castle-on-the-grid/problem",
        topics: ["BFS", "Graph"],
        notes: "BFS by rook-like expansions.",
      },
      {
        title: "Roads and Libraries",
        difficulty: "Hard",
        solutionLink:
          "https://www.hackerrank.com/challenges/torque-and-development/problem",
        topics: ["Graph", "DFS"],
        notes: "Connected components and cost comparison.",
      },
      {
        title: "Poisonous Plants",
        difficulty: "Hard",
        solutionLink:
          "https://www.hackerrank.com/challenges/poisonous-plants/problem",
        topics: ["Stack", "Dynamic Programming"],
        notes: "Monotonic stack tracking death days.",
      },
    ],
  },
  {
    platform: "GeeksForGeeks",
    items: [
      {
        title: "Kadane's Algorithm GFG",
        difficulty: "Easy",
        solutionLink:
          "https://www.geeksforgeeks.org/problems/kadanes-algorithm-1587115620/1",
        topics: ["Array", "Dynamic Programming"],
        notes: "Track best ending here and global best.",
      },
      {
        title: "Subarray with given sum",
        difficulty: "Easy",
        solutionLink:
          "https://www.geeksforgeeks.org/problems/subarray-with-given-sum-1587115621/1",
        topics: ["Sliding Window", "Array"],
        notes: "Two-pointer window for positive integers.",
      },
      {
        title: "Leaders in an array",
        difficulty: "Easy",
        solutionLink:
          "https://www.geeksforgeeks.org/problems/leaders-in-an-array-1587115620/1",
        topics: ["Array"],
        notes: "Scan from right maintaining max.",
      },
      {
        title: "Reverse an Array",
        difficulty: "Easy",
        solutionLink:
          "https://www.geeksforgeeks.org/problems/reverse-an-array/1",
        topics: ["Array", "Two Pointers"],
        notes: "Swap symmetric indices.",
      },
      {
        title: "Count pairs with given sum",
        difficulty: "Easy",
        solutionLink:
          "https://www.geeksforgeeks.org/problems/count-pairs-with-given-sum5022/1",
        topics: ["Hash Table", "Array"],
        notes: "Frequency map pair counting.",
      },
      {
        title: "Union of Two Sorted Arrays",
        difficulty: "Easy",
        solutionLink:
          "https://www.geeksforgeeks.org/problems/union-of-two-sorted-arrays-1587115621/1",
        topics: ["Array", "Two Pointers"],
        notes: "Merge-like traversal skipping duplicates.",
      },
      {
        title: "Intersection of Two Arrays",
        difficulty: "Medium",
        solutionLink:
          "https://www.geeksforgeeks.org/problems/intersection-of-two-arrays2404/1",
        topics: ["Array", "Hash Table"],
        notes: "Set-based lookup or sorted two-pointer.",
      },
      {
        title: "Majority Element GFG",
        difficulty: "Medium",
        solutionLink:
          "https://www.geeksforgeeks.org/problems/majority-element-1587115620/1",
        topics: ["Array", "Voting"],
        notes: "Boyer-Moore with optional validation.",
      },
      {
        title: "Missing number in array",
        difficulty: "Medium",
        solutionLink:
          "https://www.geeksforgeeks.org/problems/missing-number-in-array1416/1",
        topics: ["Math", "Bit Manipulation"],
        notes: "Gauss sum or XOR approach.",
      },
      {
        title: "Kth smallest element",
        difficulty: "Medium",
        solutionLink:
          "https://www.geeksforgeeks.org/problems/kth-smallest-element5635/1",
        topics: ["Heap", "Quickselect"],
        notes: "Min-heap or partition-based selection.",
      },
      {
        title: "Minimum platforms",
        difficulty: "Medium",
        solutionLink:
          "https://www.geeksforgeeks.org/problems/minimum-platforms-1587115620/1",
        topics: ["Greedy", "Sorting"],
        notes: "Sort arrivals/departures and sweep.",
      },
      {
        title: "Merge Without Extra Space",
        difficulty: "Medium",
        solutionLink:
          "https://www.geeksforgeeks.org/problems/merge-two-sorted-arrays-1587115620/1",
        topics: ["Array", "Gap Method"],
        notes: "Shell-sort-like gap reduction strategy.",
      },
      {
        title: "0 - 1 Knapsack Problem",
        difficulty: "Hard",
        solutionLink:
          "https://www.geeksforgeeks.org/problems/0-1-knapsack-problem0945/1",
        topics: ["Dynamic Programming", "Knapsack"],
        notes: "DP by capacity and item index.",
      },
      {
        title: "Topological sort",
        difficulty: "Hard",
        solutionLink:
          "https://www.geeksforgeeks.org/problems/topological-sort/1",
        topics: ["Graph", "Topological Sort"],
        notes: "Kahn's algorithm or DFS postorder.",
      },
      {
        title: "Dijkstra Algorithm",
        difficulty: "Hard",
        solutionLink:
          "https://www.geeksforgeeks.org/problems/implementing-dijkstra-set-1-adjacency-matrix/1",
        topics: ["Graph", "Shortest Path", "Heap"],
        notes: "Min-priority queue with distance relaxation.",
      },
    ],
  },
];

const NON_LEETCODE_SEED_PROBLEMS = NON_LEETCODE_BLUEPRINT.flatMap(
  (group, groupIndex) =>
    group.items.map((item, itemIndex) => {
      const offset = groupIndex * 15 + itemIndex;
      const date = new Date(Date.UTC(2025, 4, 1 + offset))
        .toISOString()
        .slice(0, 10);
      const solved = item.difficulty !== "Hard" && itemIndex % 4 !== 0;

      return {
        title: item.title,
        difficulty: item.difficulty,
        platform: group.platform,
        topics: item.topics,
        companyTags: [],
        status: solved ? "Solved" : "Unsolved",
        solutionLink: item.solutionLink,
        notes: item.notes,
        attempts: solved ? 1 + (itemIndex % 3) : 0,
        dateAdded: date,
        solvedDate: solved ? date : null,
      };
    }),
);

const ALL_SEED_PROBLEMS = [...SEED_PROBLEMS, ...NON_LEETCODE_SEED_PROBLEMS];

// ─── POST /api/seed/problems — seeds 75 problems for the logged-in user ────────
router.post("/seed/problems", requireAuth, async (req, res): Promise<void> => {
  const userId = req.user!.userId;

  // Skip if already has problems
  const existing = await db
    .select({ title: problemsTable.title })
    .from(problemsTable)
    .where(eq(problemsTable.userId, userId));

  const existingTitles = new Set(
    existing.map((e: any) => e.title.toLowerCase()),
  );
  const toInsert = ALL_SEED_PROBLEMS.filter(
    (p) => !existingTitles.has(p.title.toLowerCase()),
  );

  if (toInsert.length === 0) {
    res.json({
      message: "Already seeded — no new problems to add.",
      inserted: 0,
      total: existing.length,
    });
    return;
  }

  const today = new Date().toISOString().slice(0, 10);
  const rows = toInsert.map((p) => ({
    userId,
    title: p.title,
    difficulty: p.difficulty,
    platform: p.platform,
    topics: [...p.topics],
    companyTags: [...p.companyTags],
    status: p.status,
    favorite: false,
    bookmark: false,
    notes: p.notes,
    solutionLink: p.solutionLink,
    dateAdded: p.dateAdded ?? today,
    solvedDate: p.solvedDate ?? null,
    attempts: p.attempts ?? 0,
  }));

  await db.insert(problemsTable).values(rows);

  const stats = {
    Easy: rows.filter((r) => r.difficulty === "Easy").length,
    Medium: rows.filter((r) => r.difficulty === "Medium").length,
    Hard: rows.filter((r) => r.difficulty === "Hard").length,
  };

  res.status(201).json({
    message: `Seeded ${rows.length} problems successfully!`,
    inserted: rows.length,
    skipped: toInsert.length - rows.length,
    breakdown: stats,
    total: existing.length + rows.length,
  });
});

export default router;
